
name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run Behave tests
    #   run: |
    #     behave

    - name: Run Behave tests
      run: |
        behave --format json --outfile=reports/cucumber.json ./features

    - name: Convert JSON to HTML
      run: |
        npm install -g cucumber-html-reporter
        cucumber-html-reporter --input reports/cucumber.json --output reports/cucumber-report.html

    - name: Upload Cucumber Report
      uses: actions/upload-artifact@v2
      with:
        name: cucumber-report
        path: reports/cucumber-report.html

    - name: Test Summary
      uses: dorny/test-summary@v1
      with:
        check_name: 'Test Report'
        report_paths: '**/reports/*.xml'







